name: test-action

on:
  push:
    branches: [ "patch-1" ]
  pull_request:
    branches: [ "patch-1" ]

jobs:
   test: 
      runs-on: ubuntu-latest
      steps:
        - name: Test another repo
          uses: samsmithnz/deployment-frequency@main
          with:
            workflows: ''
            owner-repo: 'anshu-makkar/101'
            default-branch: 'patch-1'
            number-of-days: 30
